python create_tables.py
python parse_tweets.py
python parse_camera.py
python parse_images.py
python parse_obj_det.py
python convert_alerts.py
python convert_jams.py
python parse_alerts.py
python parse_jams.py
